Ліпешко Сергій Васильович ФІТ 4-4

In [1]:
#1 Створіть одновимірний масив (вектор) з найбільшими простими числами, не перевищуючи 30, та виведіть його значення.
def is_prime(num):
    """Функція для перевірки, чи є число простим."""
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

def generate_primes_up_to_n(n):
    """Генерує прості числа, не більше заданого n."""
    primes = [i for i in range(2, n+1) if is_prime(i)]
    return primes

max_value = 30


prime_numbers = generate_primes_up_to_n(max_value)


print("Масив найбільших простих чисел, не більше", max_value, ":", prime_numbers)


Масив найбільших простих чисел, не більше 30 : [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


In [2]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратів найближчого більшого парного числа для кожного натурального числа, починаючи з 1, та виведіть його значення.
import math

def next_even_square(num):
    """Знаходить квадрат найближчого більшого парного числа."""
    even_num = math.ceil(math.sqrt(num))
    if even_num % 2 == 1:
        even_num += 1
    return even_num**2


rows, cols = 3, 3


matrix = [[0] * cols for _ in range(rows)]


current_num = 1
for i in range(rows):
    for j in range(cols):
        matrix[i][j] = next_even_square(current_num)
        current_num += 1


for row in matrix:
    print(row)


[4, 4, 4]
[4, 16, 16]
[16, 16, 16]


In [3]:
# 3 Створіть масив розміром 6x6, заповніть його випадковими цілими числами від -50 до 50 та знайдіть добуток непарних чисел.
import numpy as np

# Розмір матриці
rows, cols = 6, 6

# Ініціалізація матриці випадковими цілими числами від -50 до 50
matrix = np.random.randint(-50, 51, size=(rows, cols))

# Виведення матриці
print("Матриця:")
print(matrix)

# Знаходження добутку непарних чисел
product_of_odd_numbers = 1
for row in matrix:
    for num in row:
        if num % 2 != 0:
            product_of_odd_numbers *= num

# Виведення добутку непарних чисел
print("\nДобуток непарних чисел:", product_of_odd_numbers)


Матриця:
[[-32 -34 -48  -4  25 -13]
 [ 19 -47  -8 -20  48 -18]
 [-42  49 -22   3 -22 -30]
 [  0  19  34  23  50 -50]
 [ 30 -36  38  10  50  21]
 [  2 -11  27 -44 -35 -20]]

Добуток непарних чисел: -1876949239


C:\Users\siroz\AppData\Local\Temp\ipykernel_15628\573135128.py:19: RuntimeWarning: overflow encountered in scalar multiply
  product_of_odd_numbers *= num


In [4]:
# 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить максимальні елементи в кожному стовпці.
import numpy as np

# Розмір матриці
rows, cols = 4, 4

# Ініціалізація матриці випадковими дійсними числами від 0 до 1
matrix = np.random.rand(rows, cols)

# Виведення матриці
print("Матриця:")
print(matrix)

# Знаходження вектора-рядка з максимальними елементами в кожному стовпці
max_elements_vector = np.max(matrix, axis=0)

# Виведення вектора-рядка
print("\nВектор-рядок з максимальними елементами в кожному стовпці:")
print(max_elements_vector)


Матриця:
[[0.43433237 0.37891051 0.8870602  0.46145319]
 [0.55429586 0.206119   0.18817487 0.17181254]
 [0.92024787 0.08319544 0.10841507 0.68715755]
 [0.23128465 0.35580619 0.55012077 0.60801217]]

Вектор-рядок з максимальними елементами в кожному стовпці:
[0.92024787 0.37891051 0.8870602  0.68715755]


In [5]:
# 5 Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
import numpy as np

# Розмір масиву
size = 7

# Ініціалізація двох масивів випадковими цілими числами від -10 до 10
array1 = np.random.randint(-10, 11, size=size)
array2 = np.random.randint(-10, 11, size=size)

# Виведення масивів
print("Масив 1:", array1)
print("Масив 2:", array2)

# Поелементне додавання
sum_result = np.add(array1, array2)
print("\nРезультат додавання:", sum_result)

# Поелементне віднімання
subtract_result = np.subtract(array1, array2)
print("Результат віднімання:", subtract_result)

# Поелементне множення
multiply_result = np.multiply(array1, array2)
print("Результат множення:", multiply_result)


Масив 1: [ 6 -4 -6  5  0  3 -9]
Масив 2: [-2  5 -2  2  8 -9  3]

Результат додавання: [ 4  1 -8  7  8 -6 -6]
Результат віднімання: [  8  -9  -4   3  -8  12 -12]
Результат множення: [-12 -20  12  10   0 -27 -27]


In [6]:
# 6 Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.
import numpy as np

# Розмір векторів
size = 7

# Ініціалізація двох векторів довільними цілими числами
vector1 = np.random.randint(-10, 11, size=size)
vector2 = np.random.randint(-10, 11, size=size)

# Виведення векторів
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)

# Знаходження скалярного добутку
dot_product = np.dot(vector1, vector2)
print("\nСкалярний добуток:", dot_product)


Вектор 1: [ -2  10 -10  -4  -6  -4   6]
Вектор 2: [-10   2   3  -5  -6  -9   6]

Скалярний добуток: 138


In [7]:
# 7 Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
import numpy as np

# Розмір матриць
rows1, cols1 = 4, 2
rows2, cols2 = 2, 2

# Ініціалізація двох матриць випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(rows1, cols1))
matrix2 = np.random.randint(1, 11, size=(rows2, cols2))

# Виведення матриць
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

# Перемноження матриць
product_matrix = np.dot(matrix1, matrix2)

# Виведення результату перемноження
print("\nРезультат перемноження:")
print(product_matrix)


Матриця 1:
[[ 5  2]
 [ 6  2]
 [10  6]
 [10  5]]

Матриця 2:
[[7 6]
 [4 2]]

Результат перемноження:
[[43 34]
 [50 40]
 [94 72]
 [90 70]]


In [8]:
# 8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.
import numpy as np

# Розмір матриці
rows, cols = 2, 2

# Ініціалізація матриці випадковими цілими числами від 1 до 7
matrix = np.random.randint(1, 8, size=(rows, cols))

# Виведення початкової матриці
print("Початкова матриця:")
print(matrix)

# Знаходження оберненої матриці
inverse_matrix = np.linalg.inv(matrix)

# Виведення оберненої матриці
print("\nОбернена матриця:")
print(inverse_matrix)


Початкова матриця:
[[2 5]
 [3 2]]

Обернена матриця:
[[-0.18181818  0.45454545]
 [ 0.27272727 -0.18181818]]


In [9]:
# 9 Створіть матрицю розміром 3x5, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.
import numpy as np

# Розмір матриці
rows, cols = 3, 5

# Ініціалізація матриці випадковими числами від 0 до 1
matrix = np.random.rand(rows, cols)

# Виведення початкової матриці
print("Початкова матриця:")
print(matrix)

# Транспонування матриці
transposed_matrix = np.transpose(matrix)

# Виведення транспонованої матриці
print("\nТранспонована матриця:")
print(transposed_matrix)


Початкова матриця:
[[0.67900036 0.45288749 0.82911238 0.7714587  0.15540735]
 [0.45076758 0.66610707 0.39478824 0.29447838 0.64377446]
 [0.18786596 0.34919412 0.95250308 0.1657226  0.08905219]]

Транспонована матриця:
[[0.67900036 0.45076758 0.18786596]
 [0.45288749 0.66610707 0.34919412]
 [0.82911238 0.39478824 0.95250308]
 [0.7714587  0.29447838 0.1657226 ]
 [0.15540735 0.64377446 0.08905219]]


In [10]:
# 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import numpy as np

# Розмір матриці
rows, cols = 3, 4

# Ініціалізація матриці випадковими дійсними числами від 0 до 1
matrix = np.random.rand(rows, cols)

# Ініціалізація вектора випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=cols)

# Виведення матриці та вектора
print("Матриця:")
print(matrix)

print("\nВектор:")
print(vector)

# Знаходження добутку матриці на вектор
result = np.dot(matrix, vector)

# Виведення результату
print("\nРезультат добутку матриці на вектор:")
print(result)


Матриця:
[[0.1269946  0.16505806 0.96796548 0.01223188]
 [0.71355143 0.85091992 0.38093169 0.11355753]
 [0.99592872 0.95141939 0.38206757 0.59693254]]

Вектор:
[ 1 10  1  9]

Результат добутку матриці на вектор:
[ 2.8556276  10.62570005 16.26458309]


In [11]:
# 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів матриці, які менше за відповідний елемент вектору.
import numpy as np

# Розмір матриці та вектора
rows, cols = 2, 3

# Ініціалізація матриці випадковими дійсними числами від 0 до 1
matrix = np.random.rand(rows, cols)

# Ініціалізація вектора випадковими дійсними числами від 0 до 1
vector = np.random.rand(cols)

# Виведення матриці та вектора
print("Матриця:")
print(matrix)

print("\nВектор:")
print(vector)

# Знаходження суми елементів матриці, які менше за відповідний елемент вектору
sum_below_vector = np.sum(matrix[matrix < vector.reshape(1, -1)])

# Виведення результату
print("\nСума елементів матриці, які менше за відповідний елемент вектору:", sum_below_vector)


Матриця:
[[0.61213873 0.00592104 0.57618213]
 [0.90135567 0.41861738 0.2420791 ]]

Вектор:
[0.92690288 0.96634042 0.24063006]

Сума елементів матриці, які менше за відповідний елемент вектору: 1.9380328113920862


In [12]:
# 12 Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю елементів першого стовпця першої матриці.
import numpy as np

# Розмір матриць
rows, cols = 8, 8

# Ініціалізація двох матриць випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(rows, cols))
matrix2 = np.random.randint(1, 11, size=(rows, cols))

# Виведення першої матриці
print("Перша матриця:")
print(matrix1)

# Знаходження різниці елементів першого стовпця першої матриці
difference_first_column = matrix1[:, 0]

# Виведення результату
print("\nРізниця елементів першого стовпця першої матриці:")
print(difference_first_column)


Перша матриця:
[[ 1  3  7  6  1  5  5  1]
 [ 1  2  1  1  3  8  3  7]
 [ 8  2  5  2 10 10  3  2]
 [ 7  4  9  2  9  9  7  2]
 [10  6  9  6  2  5  5  6]
 [ 2  9  9  1  2  9  6  6]
 [ 9  2  5  1  1  7  6  3]
 [ 9  2  9  2  3  9  5 10]]

Різниця елементів першого стовпця першої матриці:
[ 1  1  8  7 10  2  9  9]


In [13]:
# 13 Створіть дві матриці розміром 7x7, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть добуток їх елементів.
import numpy as np

# Розмір матриць
rows, cols = 7, 7

# Ініціалізація двох матриць випадковими дійсними числами від -1 до 1
matrix1 = np.random.uniform(-1, 1, size=(rows, cols))
matrix2 = np.random.uniform(-1, 1, size=(rows, cols))

# Виведення матриць
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

# Знаходження добутку елементів матриць
product_matrix = np.multiply(matrix1, matrix2)

# Виведення результату
print("\nДобуток елементів матриць:")
print(product_matrix)


Матриця 1:
[[-0.32824205  0.73163118 -0.17031375 -0.35294808 -0.68489166 -0.24783877
   0.33645828]
 [-0.64069135  0.64690373 -0.64814582 -0.54292328 -0.91550152  0.80844731
   0.66441826]
 [ 0.6353033  -0.33418764 -0.26382259 -0.02480994  0.67764731 -0.88919969
   0.44935255]
 [ 0.33586662  0.61991716  0.36459145  0.02922384  0.22757013 -0.15951796
   0.8525956 ]
 [-0.83610911  0.44911907 -0.94268126  0.79924796  0.80626182 -0.95159773
   0.06240155]
 [-0.38405483 -0.92829261  0.50156937  0.97416043  0.10373495  0.96820552
  -0.43703492]
 [ 0.24415315 -0.55227817 -0.13361732  0.7064128  -0.10353248  0.22371817
  -0.51572675]]

Матриця 2:
[[ 0.00975828 -0.8993618   0.20428242 -0.31367224 -0.20746822  0.18401849
  -0.38838746]
 [ 0.0412379  -0.64644743  0.20054665  0.48566451  0.63778647 -0.20239967
   0.15672538]
 [ 0.40865268  0.88380609  0.38828702 -0.25985986 -0.63929541  0.62984613
   0.96423675]
 [-0.28340801  0.35615192 -0.67332091  0.68758212 -0.91550011 -0.64803264
   0.0652145

In [14]:
# 14 Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть добуток елементів матриці, які більше за їх середнє арифметичне значення.
import numpy as np

# Розмір матриці
rows, cols = 7, 7

# Ініціалізація матриці випадковими дійсними числами від -10 до 10
matrix = np.random.uniform(-10, 10, size=(rows, cols))

# Виведення матриці
print("Матриця:")
print(matrix)

# Знаходження середнього арифметичного значення
average_value = np.mean(matrix)

# Знаходження добутку елементів матриці, які більше за середнє арифметичне
product_of_greater_than_average = np.prod(matrix[matrix > average_value])

# Виведення результату
print("\nДобуток елементів матриці, які більше за середнє арифметичне:")
print(product_of_greater_than_average)


Матриця:
[[-9.94879385  0.95310629 -1.70516405 -5.66457167  9.79233017  8.45472133
  -7.89732288]
 [ 4.15885844 -9.12008819 -9.61429444  9.10270874 -8.38500263 -5.29459261
  -3.62056865]
 [-3.4993606   9.13652356 -3.08528295  1.81360368 -0.51550306  1.79908207
   9.18763696]
 [-9.47020124  7.54734044 -3.82647994 -8.64963044 -7.98989406 -6.80318354
  -0.87454532]
 [-5.01793712 -4.21460889  5.03115945  1.02461962  7.41318508 -6.67533839
  -4.88045327]
 [-5.97037958 -9.24504335 -4.79373794  0.95082647 -4.40412526 -1.57557284
   0.85211485]
 [-1.55530337 -0.25656047 -0.67098412  8.56671692  5.27652662  1.98755335
  -8.75312141]]

Добуток елементів матриці, які більше за середнє арифметичне:
1333139063.1149402


In [15]:
# 15 Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить найбільше за модулем ціле значення в кожному рядку матриці.
import numpy as np

# Розмір матриці
rows, cols = 9, 9

# Ініціалізація матриці випадковими дійсними числами від -0.5 до 0.5
matrix = np.random.uniform(-0.5, 0.5, size=(rows, cols))

# Виведення матриці
print("Матриця:")
print(matrix)

# Знаходження вектора-стовпчика з найбільшими за модулем цілими значеннями в кожному рядку
max_abs_values_vector = np.max(np.abs(matrix), axis=1)

# Виведення результату
print("\nВектор-стовпчик з найбільшими за модулем цілими значеннями в кожному рядку:")
print(max_abs_values_vector)


Матриця:
[[-0.25823801 -0.44341022 -0.17812493  0.34346999  0.16534379  0.01940691
  -0.24174678  0.2497653   0.10187383]
 [-0.1994171   0.4930037  -0.22088069  0.26117157 -0.19467769 -0.36398699
  -0.04510062 -0.22992496  0.3942778 ]
 [-0.14912356  0.19703364 -0.17137135 -0.0603109  -0.09557079  0.36532575
  -0.28092817  0.17451596 -0.06104381]
 [-0.26065068 -0.25397371  0.03063496  0.13884194 -0.46046809  0.34323204
  -0.07263516  0.36415032 -0.15231744]
 [-0.39674182  0.03232638  0.21637544 -0.35448665  0.01453842 -0.3139918
  -0.47990975 -0.22188496 -0.47353838]
 [ 0.47446725 -0.01962445 -0.43835146  0.00331024 -0.18331139 -0.1631234
   0.01428429  0.0143269   0.15634103]
 [ 0.26665718  0.05388239  0.45378982  0.0606165  -0.08757899  0.14072031
   0.21339635 -0.19810873 -0.04843496]
 [ 0.45908408 -0.09872163 -0.25341391 -0.0257757   0.10216251 -0.12606629
   0.27250187 -0.265453    0.47763842]
 [ 0.26975181  0.42510512 -0.20688371  0.4284451  -0.32885353 -0.49738158
  -0.26374043 -